# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fastbrew < Formula
  desc "A lightning-fast wrapper for Homebrew (Linuxbrew)"
  homepage "https://github.com/kasyap1234/fastbrew"
  version "1.2.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v1.2.0/fastbrew_Darwin_x86_64.tar.gz"
      sha256 "79c0e6a130e819b814cb4989e078b4da6fab03fc76bdf2cc8a1180357d669ea8"

      def install
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v1.2.0/fastbrew_Darwin_arm64.tar.gz"
      sha256 "ce7ba31eaff86036636a97c3d4de94d8daebb2e68696e4b0e1bdc799be785052"

      def install
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v1.2.0/fastbrew_Linux_x86_64.tar.gz"
      sha256 "5ebc92fbf18a6c8794963ee68a1b3cf28f0d9a9e5e577356da32f7f89e7aa920"
      def install
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v1.2.0/fastbrew_Linux_arm64.tar.gz"
      sha256 "9dc95965d22ea13b824dd5760c37fabb1c512790c3f732c57a2201873cb571b8"
      def install
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
  end
end
