# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fastbrew < Formula
  desc "A lightning-fast wrapper for Homebrew (Linuxbrew)"
  homepage "https://github.com/kasyap1234/fastbrew"
  version "0.3.2"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v0.3.2/fastbrew_Darwin_x86_64.tar.gz"
      sha256 "525bcc8b7859d82c60d246ebc0b4b1261816ba4135d0f35860a9455784d79715"

      def install
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v0.3.2/fastbrew_Darwin_arm64.tar.gz"
      sha256 "fdbe1d40929020da409974744da9da091a96f1107dedad5913b21de285b5fba4"

      def install
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v0.3.2/fastbrew_Linux_x86_64.tar.gz"
      sha256 "1adf4885d7dcb5a4fbb1729fbaf76bffc6a4b468cd20bf34c10713b70a62a12f"
      def install
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v0.3.2/fastbrew_Linux_arm64.tar.gz"
      sha256 "99a2f65afb39d5c278bf7f6cad8a1a9c02727978c551a0bbdaa66993e2058125"
      def install
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
  end
end
