# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fastbrew < Formula
  desc "A lightning-fast wrapper for Homebrew (Linuxbrew)"
  homepage "https://github.com/kasyap1234/fastbrew"
  version "1.5.5"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v1.5.5/fastbrew_Darwin_x86_64.tar.gz"
      sha256 "d9d2ebb2a996c6667c369b53e09b962892cb5d05b8a9d0371b18ec02010688ca"

      define_method(:install) do
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v1.5.5/fastbrew_Darwin_arm64.tar.gz"
      sha256 "20b863642b8d68a3b96b5408e18fd77e7320808a9f96f462e83390bc62762bbb"

      define_method(:install) do
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v1.5.5/fastbrew_Linux_x86_64.tar.gz"
      sha256 "b2c5e67395e69155517dc23da41ef430f27e81e3b681abb2dc8f08ab6852203f"
      define_method(:install) do
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kasyap1234/fastbrew/releases/download/v1.5.5/fastbrew_Linux_arm64.tar.gz"
      sha256 "c373bfcde08174b987f65055ee255a093364ade47a9cecfb14f3c3a939e39bca"
      define_method(:install) do
        bin.install "fastbrew"
        # Install completions (optional, if we generate them)
        # bash_completion.install "completions/fastbrew.bash" => "fastbrew"
        # zsh_completion.install "completions/fastbrew.zsh" => "_fastbrew"
        # fish_completion.install "completions/fastbrew.fish"
      end
    end
  end
end
